### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by ecoue** [Prometheus-X-association/dataspace-connector#27]
Hello folks!

We are currently working on the integration of the dataspace-connector. Unfortunately, the latest version (v1.6.0-beta.1) seems to have introduced a bug in a Docker configuration file. It looks like some file paths need to be adjusted.

```
dataspace-connector  | node:internal/modules/cjs/loader:1252
dataspace-connector  |   throw err;
dataspace-connector  |   ^
dataspace-connector  |
dataspace-connector  | Error: Cannot find module '/docker/scripts/start.sh'
dataspace-connector  |     at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
dataspace-connector  |     at Function._load (node:internal/modules/cjs/loader:1075:27)
dataspace-connector  |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
dataspace-connector  |     at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
dataspace-connector  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
dataspace-connector  |     at node:internal/main/run_main_module:36:49 {
dataspace-connector  |   code: 'MODULE_NOT_FOUND',
dataspace-connector  |   requireStack: []
dataspace-connector  | }
dataspace-connector  |
dataspace-connector  | Node.js v22.12.0
dataspace-connector exited with code 1
```

Thank you!

**Comment by Visions-Nicolas** [comment]
Hi @ecoue,

Thank you for opening this issue. This bug has been fixed in the latest version (1.8.0) available on the main branch.
A new release has also been drafted.

I hope this helps!

**Comment by ecoue** [comment]
Are you sure the bug has been fixed? I also get the error message in version 1.8.0.

`CMD [‘/docker/scripts/start.sh’, ‘$ENV’]` is still part of `/docker/app/Dockerfile`
If I change the path to `/usr/src/app/start.sh` the file is found and the error disappears.

However, another error message appears when the connector is started:
```
dataspace-connector  | /usr/src/app/src/config/environment.ts:82
dataspace-connector  |         throw new Error(
dataspace-connector  |               ^
dataspace-connector  | Error: Error initializing environment. Could not find .env file
dataspace-connector  |     at setupEnvironment (/usr/src/app/src/config/environment.ts:82:15)
dataspace-connector  |     at main (/usr/src/app/src/index.ts:7:21)
dataspace-connector  |     at Object.<anonymous> (/usr/src/app/src/index.ts:13:5)
dataspace-connector  |     at Module._compile (node:internal/modules/cjs/loader:1565:14)
dataspace-connector  |     at Module.m._compile (/usr/src/app/node_modules/.pnpm/ts-node@10.9.2_@types+node@18.19.39_typescript@4.9.5/node_modules/ts-node/src/index.ts:1618:23)
dataspace-connector  |     at node:internal/modules/cjs/loader:1708:10
dataspace-connector  |     at Object.require.extensions.<computed> [as .ts] (/usr/src/app/node_modules/.pnpm/ts-node@10.9.2_@types+node@18.19.39_typescript@4.9.5/node_modules/ts-node/src/index.ts:1621:12)
dataspace-connector  |     at Module.load (node:internal/modules/cjs/loader:1318:32)
dataspace-connector  |     at Function._load (node:internal/modules/cjs/loader:1128:12)
dataspace-connector  |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
dataspace-connector  | [nodemon] app crashed - waiting for file changes before starting...
```

Initially my environment file was called `.env`, then I renamed it to `.env.development`.
Unfortunately, this causes yet another error.

```
WARN[0000] The "NODE_ENV" variable is not set. Defaulting to a blank string.
WARN[0000] The "PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "MONGO_URI" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'ports': No port specified: 3002:<empty>
* 
```

I use the instructions at https://github.com/Prometheus-X-association/dataspace-connector
Am I missing something?

**Comment by Visions-Nicolas** [comment]
Hi, thanks for the additional information. I was able to reproduce the error, and it was caused by a CRLF/LF .sh file conversion issue. The start.sh file was not executable inside the Docker container.

Regarding the .env error, Docker Compose seems to only use the .env file and not .env.something. Therefore, the code and documentation have been updated with version 1.8.1 (#28).
